# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='schoolname',
            field=models.CharField(max_length=30),
        ),
    ]
