# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_comment_contactus_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stories',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
