# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_auto_20160729_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
